version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend-bitespeed
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/postgres"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm start
      "

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: